### ISSUE TITLE
Option, um Schleifen zum eigenen Zustand zu verhindern

### ISSUE THREAD

**Issue by nimec01** [fmidue/sd-generate#20]
Eventuell sollte es in `SDConfig` eine Möglichkeit geben, Zustände mit Transitionen zu sich selbst zu verbieten.

Dann könnte man solche Diagramme von der Generation ausschließen:
![image](https://github.com/user-attachments/assets/140e48be-79bd-4274-9c84-17c5978521ef)

**Comment by jvoigtlaender** [comment]
Tut es erstmal auch Aufnahme von `no s : States | s in (Flows <: from).s.to` in `extraConstraint`?

**Comment by jvoigtlaender** [comment]
Das ist auch der Constraint, der unter "Bewachung" einer entsprechenden `SDConfig`-Option hier eingebaut werden könnte: https://github.com/fmidue/sd-generate/blob/1575a30d935fb396bd8cff84890e737b2b42f6b3/src/Modelling/StateDiagram/Config.hs#L343-L356

**Comment by nimec01** [comment]
> Tut es erstmal auch Aufnahme von `no s : States | s in (Flows <: from).s.to` in `extraConstraint`?

Nicht wirklich. Ich erhalte immer noch solche Diagramme:
![image](https://github.com/user-attachments/assets/b0734b17-2f25-45e2-9f77-5fb184b4fd5a)

**Comment by jvoigtlaender** [comment]
> Ich erhalte immer noch solche Diagramme:

Das wundert mich sehr. Kann ich den konkreten Alloy-Code dazu sehen?

**Comment by jvoigtlaender** [comment]
Hmm, ich bin mir gerade nicht sicher, wie Alloy Quantoren über Blöcke scoped, aber ich meinte, folgendes dort zu haben:
```alloy
let hs = HierarchicalStates, inner = hs + hs.contains |
  some ((Flows <: from).hs.to & (Nodes - inner))
  and mul[3,#inner] >= #Nodes
 and no disj f1, f2 : Flows | some (f1.derived & f2.derived)
no s : States | s in (Flows <: from).s.to
```
nicht
```alloy
let hs = HierarchicalStates, inner = hs + hs.contains |
  some ((Flows <: from).hs.to & (Nodes - inner))
  and mul[3,#inner] >= #Nodes
 and no disj f1, f2 : Flows | some (f1.derived & f2.derived)
 and no s : States | s in (Flows <: from).s.to
```
In Ihrer Version könnte das `no s : States ...` innerhalb des `no disj f1, f2 : ...` Kontexts gefangen sein, was ja dann den logischen Gehalt der Gesamtaussage durchaus ändert (und daher der No-Loops-Constraint vielleicht keine Wirkung entfaltet).

**Comment by jvoigtlaender** [comment]
Übrigens hätte ich wohl auch das
```alloy
no disj f1, f2 : Flows | some (f1.derived & f2.derived)
```
auf die oberste Ebene gezogen, statt es mit `and` an einen inneren Kontext zu konkatenieren. Vermutlich macht das konkret aber keinen Unterschied, weil zumindest kein Quantor drumherum steht (sondern nur ein `let`).

**Comment by nimec01** [comment]
> Hmm, ich bin mir gerade nicht sicher, wie Alloy Quantoren über Blöcke scoped, aber ich meinte, folgendes dort zu haben:
> 
> ```alloy
> let hs = HierarchicalStates, inner = hs + hs.contains |
>   some ((Flows <: from).hs.to & (Nodes - inner))
>   and mul[3,#inner] >= #Nodes
>  and no disj f1, f2 : Flows | some (f1.derived & f2.derived)
> no s : States | s in (Flows <: from).s.to
> ```
> 
> nicht
> 
> ```alloy
> let hs = HierarchicalStates, inner = hs + hs.contains |
>   some ((Flows <: from).hs.to & (Nodes - inner))
>   and mul[3,#inner] >= #Nodes
>  and no disj f1, f2 : Flows | some (f1.derived & f2.derived)
>  and no s : States | s in (Flows <: from).s.to
> ```
> 
> In Ihrer Version könnte das `no s : States ...` innerhalb des `no disj f1, f2 : ...` Kontexts gefangen sein, was ja dann den logischen Gehalt der Gesamtaussage durchaus ändert (und daher der No-Loops-Constraint vielleicht keine Wirkung entfaltet).

Ja, das war das Problem. Die Schleifen werden nun auch ausgeschlossen.
