### ISSUE TITLE
Derive `Ord` for `StateDiagram` and `UMLStateDiagram`

### ISSUE THREAD

**Issue by nimec01** [fmidue/sd-generate#6]
Is there any specific reason why these types are not deriving `Ord`?

Standalone deriving does not work since "The data constructors of ‘UMLStateDiagram’ are not all in scope"

**Comment by jvoigtlaender** [comment]
The short answer probably is that it wasn't needed so far. As in, there was no API use case for comparing diagrams. What is it you want to do? Put them in some collection data structure that needs order for efficient access?

A slightly longer answer is that simply deriving `Ord` (or `Eq`) would probably end up in a problematic place. The point being that the abstraction `UMLStateDiagram` hides that the underlying datatype has a field `label` that doesn't really have a meaning on the outermost level. This becomes apparent, for example, here: https://github.com/fmidue/sd-generate/blob/278d13cc403eb69a0da629c92a9227b2b1caffa6/src/Modelling/StateDiagram/Datatype.hs#L139-L146
If a diagram output by that function would be passed to a derived `==` operation, a runtime error would occur.

So instead, `Eq` (or `Ord`) on `UMLStateDiagram` would have to be a custom definition that uses `unUML` and then progresses with the components except for `label`.

But the question really remains what the purpose of said `Eq` or `Ord` instance would be and what the correct semantics for that purpose would be. For example, in some instances in testing, one might want that `==` says two diagrams are equal if they only differ by consistent renaming of labels or rearrangement of substate lists. A derived instance would have a different meaning.

**Comment by nimec01** [comment]
I am currently using a Map with `StateDiagram` (standalone deriving works here). There was another case that required `UMLStateDiagram` to derive `Ord`, but that is not required anymore. 

> If a diagram output by that function would be passed to a derived == operation, a runtime error would occur.
So instead, Eq (or Ord) on UMLStateDiagram would have to be a custom definition that uses unUML and then progresses with the components except for label.

That makes sense. I will then define my own instance when necessary.
