### ISSUE TITLE
`output-blocks` Upgrade

### ISSUE THREAD

**Issue by nimec01** [fmidue/sd-generate#7]
Derzeit nutzt dieses Repo noch `output-monad`.  Damit es in anderen packages nicht zu dependency clashes kommt, sollte auf die aktuellste Version von `output-blocks` geupgradet werden.

**Comment by jvoigtlaender** [comment]
Makes sense. Can you do a pull request? Hopefully https://github.com/fmidue/logic-tasks/commit/163bca49794eed48d4da3eb2849b03f58431e9d1 provides enough guidance on what needs to be changed for that.
